server {
  listen 8000;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = / {
    try_files /insta_backtester_frontend/index.html /index.html =404;
  }

  location /insta_backtester_frontend/ {
    alias /usr/share/nginx/html/insta_backtester_frontend/;
    try_files $uri $uri/ /insta_backtester_frontend/index.html;
  }

  location / {
    try_files $uri $uri/ /insta_backtester_frontend/index.html;
  }
}
